package com.mos.backend.common.event;

public enum EventType {
    FILE_UPLOADED,
    FILE_UPLOAD_FAILED,
    STUDY_CREATED,
    STUDY_LIKED,
    STUDY_LIKE_CANCELED,
    STUDY_VIEWED,
    STUDY_JOIN_REQUESTED,
    STUDY_JOIN_CANCELED,
    STUDY_JOIN_REJECTED,
    STUDY_JOIN_APPROVED,
    STUDY_DELETED,
    STUDY_UPDATED,
    IMPORTANT_NOTICE_CHANGED,
    STUDY_MEMBER_CREATED,
}
