spring:
    config:
        import: optional:classpath:local.env[.properties]

datasource:
    url: jdbc:mysql://localhost:3306/chatdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
    database: mysql
    generate-ddl: true
    hibernate:
        ddl-auto: create
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect

data:
    redis:
        host: 127.0.0.1
        port: 6379
