spring:
  config:
    import: optional:classpath:local.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/mos_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: 127.0.0.1
      port: 6379

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
    header: ${JWT_ACCESS_HEADER}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}
    header: ${JWT_REFRESH_HEADER}
